"""Iniciando as tabelas

Revision ID: e4c4a5d855e1
Revises: 
Create Date: 2025-08-06 20:01:58.877586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c4a5d855e1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_Mesorregiao', schema=None) as batch_op:
        batch_op.alter_column('mesorregiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('tb_Microrregiao', schema=None) as batch_op:
        batch_op.alter_column('microrregiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('codmesorregiao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)

    with op.batch_alter_table('tb_Municipio', schema=None) as batch_op:
        batch_op.alter_column('nomemunicipio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('codmesorregiao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('codmicrorregiao',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('tb_UF', schema=None) as batch_op:
        batch_op.alter_column('uf',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('nomeestado',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.execute("UPDATE tb_instituicao SET uf = 'NULL' WHERE uf IS NULL")
    with op.batch_alter_table('tb_instituicao', schema=None) as batch_op:
        batch_op.alter_column('regiao',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('codregiao',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('uf',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('municipio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('codmunicipio',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('entidade',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
        batch_op.alter_column('matriculas_base',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tb_instituicao', schema=None) as batch_op:
        batch_op.alter_column('matriculas_base',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('entidade',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('codmunicipio',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('municipio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('uf',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('codregiao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tb_UF', schema=None) as batch_op:
        batch_op.alter_column('regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('nomeestado',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('uf',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tb_Municipio', schema=None) as batch_op:
        batch_op.alter_column('codmicrorregiao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('codmesorregiao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('nomemunicipio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tb_Microrregiao', schema=None) as batch_op:
        batch_op.alter_column('regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('codmesorregiao',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('microrregiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('tb_Mesorregiao', schema=None) as batch_op:
        batch_op.alter_column('regiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('coduf',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('mesorregiao',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
